### ISSUE TITLE
Cannot Create a New Node in a Re-opened Map

### ISSUE THREAD

**Issue by SebastianBoell** [CompendiumNG/CompendiumNG#45]
http://compendium.open.ac.uk/bugzilla/show_bug.cgi?id=1014

John McGraw 2011-08-23 00:48:53 BST

When I try to create a new node of any type, I receive the following error:

Error (ViewPaneUI.CreateNode.actionPerformed)

NodeService is Null in View.addMemberNode-2c

[reply] [-] Comment 1 Michelle Bachler 2011-08-23 09:20:34 BST

Can I have a little more information?
What version of Mac OS are you on?
Have you just installed the software or have you been using it for some time
and this has just started happening?
Can you check the log files and see if they have more information
(Applications/Compendium/System/resources/Logs)?

**Comment by SebastianBoell** [comment]
Suggest closing as invalid / wontfix

**Comment by maiklos** [comment]
I agree, there is not enough information to reproduces/retest this. Closing

**Comment by joe312213** [comment]
I get the same error after re-opening an existing project, after a computer crash (so compendium did have a chance to exit cleanly). Windows 8.1, CompendiumNG 2.1.5

Here is some of the log file recording the errors:

<pre>
2014-06-27 19:22:24,734 DEBUG [AWT-EventQueue-0] c.c.ui.UIImages UIImages.java:217 loading icon id: 4 path: C:\Program Files (x86)\CompendiumNG\Skins\Default\map_sm.png
2014-06-27 19:22:24,734 DEBUG [AWT-EventQueue-0] o.c.tools.Utilities Utilities.java:153 ImageIconCache hit on: C:\Program Files (x86)\CompendiumNG\Skins\Default\map_sm.png
2014-06-28 01:05:09,875 DEBUG [AWT-EventQueue-0] c.c.ui.UINode UINode.java:528 dragEnter - about to accept DnDConstants.ACTION_LINK
2014-06-28 01:05:10,179 DEBUG [AWT-EventQueue-0] c.c.ui.UINode UINode.java:517 In drag exit of Target
2014-06-28 01:05:10,971 DEBUG [AWT-EventQueue-0] c.c.ui.UIViewPane UIViewPane.java:423 dnd drop detected: java.awt.dnd.DropTargetContext$TransferableProxy@65bb84 at location x=577, y=5668
2014-06-28 01:05:10,972 DEBUG [AWT-EventQueue-0] c.c.ui.UIViewPane UIViewPane.java:437 supported flavour: DataFlavor.stringFlavor
2014-06-28 01:05:11,263 DEBUG [UIViewPane.drop-StringFlavor] c.c.ui.UIImages UIImages.java:217 loading icon id: 8 path: C:\Program Files (x86)\CompendiumNG\Skins\Default\position.png
2014-06-28 01:05:11,264 DEBUG [UIViewPane.drop-StringFlavor] o.c.tools.Utilities Utilities.java:153 ImageIconCache hit on: C:\Program Files (x86)\CompendiumNG\Skins\Default\position.png
2014-06-28 01:05:11,266 INFO  [AWT-EventQueue-0] c.c.u.ProjectCompendiumFrame ProjectCompendiumFrame.java:6064 Error:Error: (ViewPaneUI.checkLinkRollover)
88
2014-06-28 01:05:11,266 DEBUG [UIViewPane.drop-StringFlavor] c.c.ui.UIImages UIImages.java:217 loading icon id: 8 path: C:\Program Files (x86)\CompendiumNG\Skins\Default\position.png
2014-06-28 01:05:11,266 DEBUG [UIViewPane.drop-StringFlavor] o.c.tools.Utilities Utilities.java:153 ImageIconCache hit on: C:\Program Files (x86)\CompendiumNG\Skins\Default\position.png
2014-06-28 01:05:16,730 DEBUG [AWT-EventQueue-0] c.c.ui.UIImages UIImages.java:217 loading icon id: 38 path: C:\Program Files (x86)\CompendiumNG\Skins\Default\trashbinfull.png
2014-06-28 01:05:16,731 DEBUG [AWT-EventQueue-0] o.c.tools.Utilities Utilities.java:153 ImageIconCache hit on: C:\Program Files (x86)\CompendiumNG\Skins\Default\trashbinfull.png
2014-06-28 01:05:21,700 DEBUG [AWT-EventQueue-0] c.c.c.d.s.ServiceCache ServiceCache.java:63 constructing ServiceCache...5
2014-06-28 01:05:21,701 DEBUG [AWT-EventQueue-0] c.c.c.d.s.ServiceCache ServiceCache.java:63 constructing ServiceCache...5
2014-06-28 01:05:21,701 DEBUG [AWT-EventQueue-0] c.c.c.d.s.ServiceCache ServiceCache.java:63 constructing ServiceCache...5
2014-06-28 01:05:21,701 DEBUG [AWT-EventQueue-0] c.c.c.d.s.ServiceCache ServiceCache.java:63 constructing ServiceCache...5
2014-06-28 01:05:21,701 DEBUG [AWT-EventQueue-0] c.c.c.d.s.ServiceCache ServiceCache.java:63 constructing ServiceCache...5
2014-06-28 01:05:21,702 DEBUG [AWT-EventQueue-0] c.c.c.d.s.ServiceCache ServiceCache.java:63 constructing ServiceCache...5
2014-06-28 01:05:21,702 DEBUG [AWT-EventQueue-0] c.c.c.d.s.ServiceCache ServiceCache.java:63 constructing ServiceCache...5
2014-06-28 01:05:21,702 DEBUG [AWT-EventQueue-0] c.c.c.d.s.ServiceCache ServiceCache.java:63 constructing ServiceCache...5
2014-06-28 01:05:21,702 DEBUG [AWT-EventQueue-0] c.c.c.d.s.ServiceCache ServiceCache.java:63 constructing ServiceCache...5
2014-06-28 01:05:21,702 DEBUG [AWT-EventQueue-0] c.c.c.d.s.ServiceCache ServiceCache.java:63 constructing ServiceCache...5
2014-06-28 01:05:21,703 DEBUG [AWT-EventQueue-0] c.c.c.d.s.ServiceCache ServiceCache.java:63 constructing ServiceCache...5
2014-06-28 01:05:21,703 DEBUG [AWT-EventQueue-0] c.c.c.d.s.ServiceCache ServiceCache.java:63 constructing ServiceCache...5
2014-06-28 01:05:21,703 DEBUG [AWT-EventQueue-0] c.c.c.d.s.ServiceCache ServiceCache.java:63 constructing ServiceCache...5
2014-06-28 01:05:21,703 DEBUG [AWT-EventQueue-0] c.c.c.d.s.ServiceCache ServiceCache.java:63 constructing ServiceCache...5
2014-06-28 01:05:21,703 DEBUG [AWT-EventQueue-0] c.c.c.d.s.ServiceCache ServiceCache.java:63 constructing ServiceCache...5
2014-06-28 01:05:21,704 DEBUG [AWT-EventQueue-0] c.c.c.d.s.ServiceCache ServiceCache.java:63 constructing ServiceCache...5
2014-06-28 01:05:21,704 DEBUG [AWT-EventQueue-0] c.c.c.d.s.ServiceCache ServiceCache.java:63 constructing ServiceCache...5
2014-06-28 01:05:25,106 DEBUG [ProjectCompendiumFrame.onFileOpen] c.c.ui.UIImages UIImages.java:217 loading icon id: 4 path: C:\Program Files (x86)\CompendiumNG\Skins\Default\map_sm.png
2014-06-28 01:05:25,107 DEBUG [ProjectCompendiumFrame.onFileOpen] o.c.tools.Utilities Utilities.java:153 ImageIconCache hit on: C:\Program Files (x86)\CompendiumNG\Skins\Default\map_sm.png
2014-06-28 01:05:27,851 DEBUG [AWT-EventQueue-0] c.c.c.d.m.DBAdminDerbyDatabase DBAdminDatabase.java:398 checkVersion returning: 2.0.1
2014-06-28 01:05:27,857 DEBUG [ProjectCompendiumFrame.onFileOpen] c.c.c.d.m.DBAdminDerbyDatabase DBAdminDatabase.java:398 checkVersion returning: 2.0.1
2014-06-28 01:05:27,860 DEBUG [ProjectCompendiumFrame.onFileOpen] c.c.c.d.s.ServiceManager ServiceManager.java:760 new user service generated 
2014-06-28 01:05:27,894 WARN  [ProjectCompendiumFrame.onFileOpen] c.c.c.datamodel.View NodeSummary.java:1185 Model is not initialized yet in View...
2014-06-28 01:05:27,895 WARN  [ProjectCompendiumFrame.onFileOpen] c.c.c.d.NodeSummary NodeSummary.java:1185 Model is not initialized yet in NodeSummary...
2014-06-28 01:05:27,896 WARN  [ProjectCompendiumFrame.onFileOpen] c.c.c.datamodel.View NodeSummary.java:1185 Model is not initialized yet in View...
2014-06-28 01:05:27,896 WARN  [ProjectCompendiumFrame.onFileOpen] c.c.c.d.NodeSummary NodeSummary.java:1185 Model is not initialized yet in NodeSummary...
2014-06-28 01:05:27,897 WARN  [ProjectCompendiumFrame.onFileOpen] c.c.c.d.NodeSummary NodeSummary.java:1185 Model is not initialized yet in NodeSummary...
2014-06-28 01:05:27,898 WARN  [ProjectCompendiumFrame.onFileOpen] c.c.c.d.NodeSummary NodeSummary.java:1185 Model is not initialized yet in NodeSummary...
2014-06-28 01:05:27,898 WARN  [ProjectCompendiumFrame.onFileOpen] c.c.c.d.NodeSummary NodeSummary.java:1185 Model is not initialized yet in NodeSummary...
2014-06-28 01:05:27,899 WARN  [ProjectCompendiumFrame.onFileOpen] c.c.c.datamodel.View NodeSummary.java:1185 Model is not initialized yet in View...
2014-06-28 01:05:27,899 WARN  [ProjectCompendiumFrame.onFileOpen] c.c.c.datamodel.View NodeSummary.java:1185 Model is not initialized yet in View...
2014-06-28 01:05:27,902 WARN  [ProjectCompendiumFrame.onFileOpen] c.c.c.d.NodeSummary NodeSummary.java:1185 Model is not initialized yet in NodeSummary...
2014-06-28 01:05:27,935 ERROR [ProjectCompendiumFrame.onFileOpen] c.c.u.UIMapViewFrame UIMapViewFrame.java:929 viewframe not selected because 
java.lang.NullPointerException: null
    at com.compendium.ui.toolbars.UIToolBarScribble.setScribbleThickness(UIToolBarScribble.java:616) ~[CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.compendium.ui.toolbars.UIToolBarScribble.access$300(UIToolBarScribble.java:69) ~[CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.compendium.ui.toolbars.UIToolBarScribble$3.actionPerformed(UIToolBarScribble.java:352) ~[CompendiumNG.jar:2.1.5-SNAPSHOT]
    at javax.swing.JComboBox.fireActionEvent(Unknown Source) ~[na:1.7.0_60]
    at javax.swing.JComboBox.setSelectedItem(Unknown Source) ~[na:1.7.0_60]
    at javax.swing.JComboBox.setSelectedIndex(Unknown Source) ~[na:1.7.0_60]
    at com.compendium.ui.toolbars.UIToolBarScribble.setDrawToolBarPaintEnabled(UIToolBarScribble.java:679) ~[CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.compendium.ui.toolbars.UIToolBarScribble.setEnabled(UIToolBarScribble.java:709) ~[CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.compendium.ui.toolbars.UIToolBarManager.setDrawToolBarEnabled(UIToolBarManager.java:1036) ~[CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.compendium.ui.ProjectCompendiumFrame.activateWindow(ProjectCompendiumFrame.java:6111) [CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.compendium.ui.UIViewFrame.internalFrameActivated(UIViewFrame.java:442) ~[CompendiumNG.jar:2.1.5-SNAPSHOT]
    at javax.swing.JInternalFrame.fireInternalFrameEvent(Unknown Source) [na:1.7.0_60]
    at javax.swing.JInternalFrame.setSelected(Unknown Source) [na:1.7.0_60]
    at com.compendium.ui.UIMapViewFrame.setSelected(UIMapViewFrame.java:926) ~[CompendiumNG.jar:2.1.5-SNAPSHOT]
    at javax.swing.JInternalFrame.show(Unknown Source) [na:1.7.0_60]
    at java.awt.Component.show(Unknown Source) [na:1.7.0_60]
    at java.awt.Component.setVisible(Unknown Source) [na:1.7.0_60]
    at javax.swing.JComponent.setVisible(Unknown Source) [na:1.7.0_60]
    at com.compendium.ui.ProjectCompendiumFrame.addViewToDesktop(ProjectCompendiumFrame.java:5818) [CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.compendium.ui.ProjectCompendiumFrame.addViewToDesktop(ProjectCompendiumFrame.java:5601) [CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.compendium.ui.ProjectCompendiumFrame.setNodesAndLinks(ProjectCompendiumFrame.java:5224) [CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.compendium.ui.ProjectCompendiumFrame.initializeForProject(ProjectCompendiumFrame.java:2271) [CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.compendium.ui.ProjectCompendiumFrame$4.run(ProjectCompendiumFrame.java:2251) [CompendiumNG.jar:2.1.5-SNAPSHOT]
2014-06-28 01:05:30,193 WARN  [AWT-EventQueue-0] c.c.u.t.UIToolBarZoom UIToolBarZoom.java:544 Unable to reset zoom... pane not initialized yet
2014-06-28 01:05:33,130 DEBUG [AWT-EventQueue-0] c.c.ui.UINode UINode.java:528 dragEnter - about to accept DnDConstants.ACTION_LINK
2014-06-28 01:05:33,210 DEBUG [AWT-EventQueue-0] c.c.ui.UINode UINode.java:517 In drag exit of Target
2014-06-28 01:05:33,802 DEBUG [AWT-EventQueue-0] c.c.ui.UIViewPane UIViewPane.java:423 dnd drop detected: java.awt.dnd.DropTargetContext$TransferableProxy@146cf63 at location x=694, y=5656
2014-06-28 01:05:33,803 DEBUG [AWT-EventQueue-0] c.c.ui.UIViewPane UIViewPane.java:437 supported flavour: DataFlavor.stringFlavor
2014-06-28 01:05:33,804 ERROR [UIViewPane.drop-StringFlavor] c.c.u.p.ViewPaneUI ViewPaneUI.java:1953 Exception...
com.compendium.core.datamodel.ModelSessionException: NodeService is null in View.addMemberNode-2c
    at com.compendium.core.datamodel.View.addMemberNode(View.java:1266) ~[CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.compendium.core.datamodel.View.addMemberNode(View.java:1101) ~[CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.compendium.core.datamodel.View.addMemberNode(View.java:963) ~[CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.compendium.ui.plaf.ViewPaneUI.createNode(ViewPaneUI.java:1931) [CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.compendium.ui.plaf.ViewPaneUI.createNode(ViewPaneUI.java:1900) [CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.compendium.ui.plaf.ViewPaneUI.createNode(ViewPaneUI.java:1881) [CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.compendium.ui.plaf.ViewPaneUI.addNewNode(ViewPaneUI.java:1590) [CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.compendium.ui.UIViewPane$2.run(UIViewPane.java:590) [CompendiumNG.jar:2.1.5-SNAPSHOT]
2014-06-28 01:05:33,804 INFO  [UIViewPane.drop-StringFlavor] c.c.u.ProjectCompendiumFrame ProjectCompendiumFrame.java:6064 Error:Error: (ViewPaneUI.CreateNode.actionPerformed)
 NodeService is null in View.addMemberNode-2c
2014-06-28 01:05:47,179 DEBUG [AWT-EventQueue-0] c.c.ui.UINode UINode.java:528 dragEnter - about to accept DnDConstants.ACTION_LINK
2014-06-28 01:05:47,450 DEBUG [AWT-EventQueue-0] c.c.ui.UINode UINode.java:517 In drag exit of Target
2014-06-28 01:05:47,979 DEBUG [AWT-EventQueue-0] c.c.ui.UIViewPane UIViewPane.java:423 dnd drop detected: java.awt.dnd.DropTargetContext$TransferableProxy@18515e6 at location x=725, y=5650
2014-06-28 01:05:47,979 DEBUG [AWT-EventQueue-0] c.c.ui.UIViewPane UIViewPane.java:437 supported flavour: DataFlavor.stringFlavor
2014-06-28 01:05:47,980 ERROR [UIViewPane.drop-StringFlavor] c.c.u.p.ViewPaneUI ViewPaneUI.java:1953 Exception...
com.compendium.core.datamodel.ModelSessionException: NodeService is null in View.addMemberNode-2c
    at com.compendium.core.datamodel.View.addMemberNode(View.java:1266) ~[CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.compendium.core.datamodel.View.addMemberNode(View.java:1101) ~[CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.compendium.core.datamodel.View.addMemberNode(View.java:963) ~[CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.compendium.ui.plaf.ViewPaneUI.createNode(ViewPaneUI.java:1931) [CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.compendium.ui.plaf.ViewPaneUI.createNode(ViewPaneUI.java:1900) [CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.compendium.ui.plaf.ViewPaneUI.createNode(ViewPaneUI.java:1881) [CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.compendium.ui.plaf.ViewPaneUI.addNewNode(ViewPaneUI.java:1590) [CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.compendium.ui.UIViewPane$2.run(UIViewPane.java:590) [CompendiumNG.jar:2.1.5-SNAPSHOT]
2014-06-28 01:05:47,980 INFO  [UIViewPane.drop-StringFlavor] c.c.u.ProjectCompendiumFrame ProjectCompendiumFrame.java:6064 Error:Error: (ViewPaneUI.CreateNode.actionPerformed)
 NodeService is null in View.addMemberNode-2c
2014-06-28 01:05:54,930 DEBUG [AWT-EventQueue-0] c.c.ui.UINode UINode.java:528 dragEnter - about to accept DnDConstants.ACTION_LINK
2014-06-28 01:05:55,194 DEBUG [AWT-EventQueue-0] c.c.ui.UINode UINode.java:517 In drag exit of Target
2014-06-28 01:05:55,722 DEBUG [AWT-EventQueue-0] c.c.ui.UIViewPane UIViewPane.java:423 dnd drop detected: java.awt.dnd.DropTargetContext$TransferableProxy@1a04069 at location x=763, y=5688
2014-06-28 01:05:55,723 DEBUG [AWT-EventQueue-0] c.c.ui.UIViewPane UIViewPane.java:437 supported flavour: DataFlavor.stringFlavor
2014-06-28 01:05:55,723 ERROR [UIViewPane.drop-StringFlavor] c.c.u.p.ViewPaneUI ViewPaneUI.java:1953 Exception...
com.compendium.core.datamodel.ModelSessionException: NodeService is null in View.addMemberNode-2c
    at com.compendium.core.datamodel.View.addMemberNode(View.java:1266) ~[CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.compendium.core.datamodel.View.addMemberNode(View.java:1101) ~[CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.compendium.core.datamodel.View.addMemberNode(View.java:963) ~[CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.compendium.ui.plaf.ViewPaneUI.createNode(ViewPaneUI.java:1931) [CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.compendium.ui.plaf.ViewPaneUI.createNode(ViewPaneUI.java:1900) [CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.compendium.ui.plaf.ViewPaneUI.createNode(ViewPaneUI.java:1881) [CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.compendium.ui.plaf.ViewPaneUI.addNewNode(ViewPaneUI.java:1590) [CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.compendium.ui.UIViewPane$2.run(UIViewPane.java:590) [CompendiumNG.jar:2.1.5-SNAPSHOT]
2014-06-28 01:05:55,724 INFO  [UIViewPane.drop-StringFlavor] c.c.u.ProjectCompendiumFrame ProjectCompendiumFrame.java:6064 Error:Error: (ViewPaneUI.CreateNode.actionPerformed)
 NodeService is null in View.addMemberNode-2c
2014-06-28 01:05:59,683 DEBUG [AWT-EventQueue-0] c.c.ui.UINode UINode.java:528 dragEnter - about to accept DnDConstants.ACTION_LINK
2014-06-28 01:06:00,179 DEBUG [AWT-EventQueue-0] c.c.ui.UINode UINode.java:517 In drag exit of Target
2014-06-28 01:06:00,587 DEBUG [AWT-EventQueue-0] c.c.ui.UIViewPane UIViewPane.java:423 dnd drop detected: java.awt.dnd.DropTargetContext$TransferableProxy@4b9e9b at location x=788, y=5666
2014-06-28 01:06:00,587 DEBUG [AWT-EventQueue-0] c.c.ui.UIViewPane UIViewPane.java:437 supported flavour: DataFlavor.stringFlavor
2014-06-28 01:06:00,588 ERROR [UIViewPane.drop-StringFlavor] c.c.u.p.ViewPaneUI ViewPaneUI.java:1953 Exception...
com.compendium.core.datamodel.ModelSessionException: NodeService is null in View.addMemberNode-2c
    at com.compendium.core.datamodel.View.addMemberNode(View.java:1266) ~[CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.compendium.core.datamodel.View.addMemberNode(View.java:1101) ~[CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.compendium.core.datamodel.View.addMemberNode(View.java:963) ~[CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.compendium.ui.plaf.ViewPaneUI.createNode(ViewPaneUI.java:1931) [CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.compendium.ui.plaf.ViewPaneUI.createNode(ViewPaneUI.java:1900) [CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.compendium.ui.plaf.ViewPaneUI.createNode(ViewPaneUI.java:1881) [CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.compendium.ui.plaf.ViewPaneUI.addNewNode(ViewPaneUI.java:1590) [CompendiumNG.jar:2.1.5-SNAPSHOT]
    at com.compendium.ui.UIViewPane$2.run(UIViewPane.java:590) [CompendiumNG.jar:2.1.5-SNAPSHOT]
2014-06-28 01:06:00,588 INFO  [UIViewPane.drop-StringFlavor] c.c.u.ProjectCompendiumFrame ProjectCompendiumFrame.java:6064 Error:Error: (ViewPaneUI.CreateNode.actionPerformed)
 NodeService is null in View.addMemberNode-2c
</pre>

**Comment by joe312213** [comment]
and I've just found that after the second time closing the project then restarting compendium the error goes away and I can add nodes again.

**Comment by AndreiLeman** [comment]
In CompendiumNG when I have happiness to meet this "No-way-without-exception" state it's almost always solved with restarting application. :)

**Comment by maiklos** [comment]
I will reopen this issue since there seems to be evidence that this still happens.

Andre, if you happen to learn  step by step how to get into the "No-way-without-exception" state so it can be reproduced it would be very useful to know and probably also helpful to fix it.

just a side comment. The original Compendium code was hiding (swallowing) a lot of exceptions silently. We've unhiden them in the CompendiumNG code to learn about various potential problems.

**Comment by ghost** [comment]
This is not platform specific. I am able to consistently reproduce it on Windows 7  
Java version:
java version "1.7.0_45"
Java(TM) SE Runtime Environment (build 1.7.0_45-b18)
Java HotSpot(TM) 64-Bit Server VM (build 24.45-b08, mixed mode)

Compendium version:
2.1.4 

Using MySQL

Here is how to reproduce it:
Pre-setup: 
1) Create a project.
2) Back up the project to sql.
3) Create a new project from back up created in (2).
4) Close Compendium

Flow:
1) Open Compendium. 
2) Open project created in pre-setup (1).
3) Close project. 
4) Open project created in (3).
5) Attempt to interact with the UI. For example, open a map node or insert a new node.

I receive the same error. The workaround is to close and re-open Compendium.

**Comment by SebastianBoell** [comment]
I removed the platform specific label.
